title: GenAI Web Application
description: GenAI web application with multiple pages
baseurl: "/genai-app" # the subpath of your site, e.g. /blog
url: "http://your-site-url" # the base hostname & protocol for your site
theme: jekyll-theme-primer

# Build settings
markdown: kramdown
destination: ./docs/_site

# Exclude from processing
exclude:
  - "public/"
  - "node_modules/"
  - "README.md"
  - "package.json"
  - "webpack.config.js"

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
